import type { ChallengeDefinition, ChallengeRuntime, Gesture } from '../types'

type ChallengeDraft = Omit<ChallengeDefinition, 'runtime' | 'variant' | 'expectedDuration' | 'pointerRequirement'> &
  Partial<Pick<ChallengeDefinition, 'variant' | 'expectedDuration' | 'pointerRequirement'>>

function defaultPointers(gesture: Gesture) {
  if (gesture === 'inhibition') return { min: 0, max: 0 }
  if (gesture === 'multi-touch') return { min: 2, max: 5 }
  return { min: 1, max: 1 }
}

function define(runtime: ChallengeRuntime, draft: ChallengeDraft): ChallengeDefinition {
  return {
    runtime,
    variant: 'STANDARD',
    expectedDuration: Math.max(3, draft.timeLimit - 1),
    pointerRequirement: defaultPointers(draft.gesture),
    ...draft,
  }
}

const interaction = (draft: ChallengeDraft) => define('interaction', draft)
const memory = (draft: ChallengeDraft) => define('memory', draft)
const logic = (draft: ChallengeDraft) => define('logic', draft)

export const CHALLENGES: ChallengeDefinition[] = [
  interaction({ id: 'tap-circle', name: 'Contact Sensor', kind: 'basic-tap', category: 'PRECISION', gesture: 'tap', instruction: 'TOUCH THE SENSOR', minRound: 0, timeLimit: 6, accessibility: 'Touch the large central calibration sensor.' }),
  interaction({ id: 'exact-hold', name: 'Biometric Hold', kind: 'exact-hold', category: 'TIMING', gesture: 'hold', instruction: 'HOLD FOR 1.500s', minRound: 1, timeLimit: 7, tuning: { targetMs: 1500, toleranceMs: { easy: 250, medium: 120, hard: 70 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Press and hold the sensor for exactly one point five seconds.' }),
  interaction({ id: 'stop-needle', name: 'Angular Lock', kind: 'stop-needle', category: 'TIMING', gesture: 'timing', instruction: 'LOCK IN THE SECTOR', minRound: 2, timeLimit: 7, tuning: { targetAngleDeg: 95, tolerance: { easy: 32, medium: 21, hard: 14 } }, accessibility: 'Touch when the rotating indicator enters the marked sector.' }),
  interaction({ id: 'shrinking-target', name: 'Confidence Window', kind: 'shrinking-target', category: 'PRECISION', gesture: 'tap', instruction: 'TOUCH BEFORE ZERO', minRound: 2, timeLimit: 6, accessibility: 'Touch the shrinking sensor before it disappears.' }),
  interaction({ id: 'tap-both', name: 'Bilateral Response', kind: 'simultaneous-tap', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'TOUCH BOTH SENSORS', minRound: 3, timeLimit: 7, tuning: { requiredPointers: 2, toleranceMs: { easy: 180, medium: 120, hard: 80 } }, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Touch the left and right sensors simultaneously with two distinct fingers.' }),
  interaction({ id: 'swipe-direction', name: 'Vector Response', kind: 'swipe-direction', category: 'SWIPE', gesture: 'swipe', instruction: 'SWIPE RIGHT', minRound: 3, timeLimit: 6, accessibility: 'Swipe to the right across the response field.' }),
  interaction({ id: 'distance-swipe', name: 'Distance Calibration', kind: 'distance-swipe', category: 'SWIPE', gesture: 'swipe', instruction: 'SWIPE EXACTLY 300px', minRound: 4, timeLimit: 7, tuning: { targetDistancePx: 300, tolerance: { easy: 70, medium: 42, hard: 24 } }, incompatibleRules: ['opposite-day'], accessibility: 'Swipe as close as possible to three hundred pixels in any direction.' }),
  interaction({ id: 'trace-wave', name: 'Signal Trace', kind: 'trace-path', category: 'COORDINATION', gesture: 'drag', instruction: 'TRACE THE SIGNAL', minRound: 5, timeLimit: 9, pointerRequirement: { min: 1, max: 1 }, incompatibleRules: ['two-finger-third', 'alternate-sector', 'central-contact'], accessibility: 'Maintain contact from origin to endpoint along the calibration path.' }),
  interaction({ id: 'do-nothing', name: 'Inhibition Test', kind: 'do-nothing', category: 'INHIBITION', gesture: 'inhibition', instruction: 'DO NOT TOUCH', minRound: 4, timeLimit: 5, incompatibleRules: ['two-finger-third', 'protect-pix', 'wait-for-clearance', 'alternate-sector', 'central-contact'], accessibility: 'Do not touch the screen until the inhibition test finishes.' }),
  interaction({ id: 'hold-tap', name: 'Split Attention', kind: 'hold-and-tap', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'HOLD A / TOUCH B', minRound: 7, timeLimit: 9, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Keep one finger on sensor A while touching sensor B with a different finger.' }),
  interaction({ id: 'finger-twister', name: 'Contact Matrix', kind: 'finger-twister', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'HOLD 1 + 3 / TOUCH 4', minRound: 10, timeLimit: 10, pointerRequirement: { min: 3, max: 3 }, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Hold sensors one and three, then touch sensor four with a third finger.' }),
  interaction({ id: 'finger-replace', name: 'Contact Transfer', kind: 'finger-replacement', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'REPLACE CONTACT', minRound: 9, timeLimit: 9, pointerRequirement: { min: 2, max: 2 }, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Add a second finger before lifting the first so contact is never lost.' }),
  interaction({ id: 'moving-target', name: 'Tracking Contact', kind: 'moving-target', category: 'TRACKING', gesture: 'tap', instruction: 'INTERCEPT THE SENSOR', minRound: 4, timeLimit: 7, accessibility: 'Touch the moving sensor as quickly as possible.' }),
  interaction({ id: 'runaway-target', name: 'Avoidant Sensor', kind: 'runaway-target', category: 'REACTION', gesture: 'tap', instruction: 'CONTAIN THE SENSOR', minRound: 8, timeLimit: 8, accessibility: 'Anticipate and touch the sensor as it changes position.' }),
  memory({ id: 'memory-sequence', name: 'Sequence Capture', kind: 'memory-sequence', category: 'MEMORY', gesture: 'memory', instruction: 'REPRODUCE THE SEQUENCE', minRound: 5, timeLimit: 12, tuning: { sequenceLength: { easy: 3, medium: 4, hard: 5 } }, accessibility: 'Watch the highlighted cells and reproduce their order.' }),
  memory({ id: 'reverse-memory', name: 'Reverse Sequence', kind: 'reverse-memory', category: 'MEMORY', gesture: 'memory', instruction: 'REPRODUCE IN REVERSE', minRound: 10, timeLimit: 13, tuning: { sequenceLength: { easy: 3, medium: 4, hard: 5 } }, accessibility: 'Watch the highlighted cells and touch them in reverse order.' }),
  memory({ id: 'delayed-memory', name: 'Retained Number', kind: 'delayed-memory', category: 'MEMORY', gesture: 'memory', instruction: 'REPORT THE STORED NUMBER', minRound: 11, timeLimit: 7, accessibility: 'Choose the number stored by the active memory condition.' }),
  logic({ id: 'odd-one', name: 'Anomaly Search', kind: 'odd-one-out', category: 'REACTION', gesture: 'logic', instruction: 'LOCATE THE ANOMALY', minRound: 5, timeLimit: 8, accessibility: 'Touch the one geometric sample that differs from the others.' }),
  memory({ id: 'track-target', name: 'PIX Tracking', kind: 'track-target', category: 'MASCOT', gesture: 'memory', instruction: 'TRACK PIX', minRound: 7, timeLimit: 10, accessibility: 'Watch the marked chamber and select it after the shuffle.' }),
  memory({ id: 'rhythm-copy', name: 'Rhythm Capture', kind: 'rhythm-copy', category: 'RHYTHM', gesture: 'timing', instruction: 'REPRODUCE THE PULSE', minRound: 8, timeLimit: 12, accessibility: 'Listen and watch, then reproduce the measured pulse pattern.' }),
  interaction({ id: 'tap-beat', name: 'Pulse Alignment', kind: 'tap-on-beat', category: 'TIMING', gesture: 'timing', instruction: 'TOUCH ON ALIGNMENT', minRound: 6, timeLimit: 7, tuning: { toleranceMs: { easy: 160, medium: 105, hard: 68 } }, accessibility: 'Touch when the moving pulse aligns with the fixed ring.' }),
  interaction({ id: 'red-green', name: 'Clearance Signal', kind: 'red-green', category: 'INHIBITION', gesture: 'inhibition', instruction: 'TOUCH ONLY ON CLEAR', minRound: 6, timeLimit: 8, incompatibleRules: ['avoid-red', 'wait-for-clearance'], accessibility: 'Wait through the stop state and touch only when clearance appears.' }),
  memory({ id: 'count-flashes', name: 'Flash Census', kind: 'count-flashes', category: 'MEMORY', gesture: 'memory', instruction: 'COUNT THE SIGNALS', minRound: 7, timeLimit: 11, accessibility: 'Count each flash and choose the matching number.' }),
  logic({ id: 'stroop', name: 'Attribute Conflict', kind: 'stroop', category: 'LOGIC', gesture: 'logic', instruction: 'SELECT THE INK COLOR', minRound: 8, timeLimit: 8, incompatibleRules: ['avoid-red'], accessibility: 'Choose the displayed ink color rather than the written color word.' }),
  logic({ id: 'tap-order', name: 'Ascending Samples', kind: 'tap-order', category: 'COORDINATION', gesture: 'memory', instruction: 'SELECT LOW TO HIGH', minRound: 5, timeLimit: 10, accessibility: 'Touch the numbered samples in ascending order.' }),
  interaction({ id: 'safe-path', name: 'Hazard Transfer', kind: 'safe-path', category: 'DRAG', gesture: 'drag', instruction: 'TRANSFER WITHOUT CONTACT', minRound: 7, timeLimit: 10, incompatibleRules: ['avoid-red', 'two-finger-third', 'alternate-sector', 'central-contact'], accessibility: 'Drag the sample to the endpoint without crossing a hazard.' }),
  interaction({ id: 'moving-path', name: 'Dynamic Hazard Transfer', kind: 'moving-safe-path', category: 'DRAG', gesture: 'drag', instruction: 'DODGE AND TRANSFER', minRound: 12, timeLimit: 11, incompatibleRules: ['avoid-red', 'two-finger-third', 'alternate-sector', 'central-contact'], accessibility: 'Drag the sample to the endpoint while avoiding the moving hazard.' }),
  interaction({ id: 'multi-hold', name: 'PIX Containment', kind: 'multi-object-hold', category: 'MASCOT', gesture: 'multi-touch', instruction: 'HOLD TWO / TOUCH PIX', minRound: 13, timeLimit: 10, pointerRequirement: { min: 3, max: 3 }, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Hold both anchors and touch PIX with a third finger.' }),
  interaction({ id: 'precision-drop', name: 'Center Placement', kind: 'precision-drop', category: 'PRECISION', gesture: 'drag', instruction: 'RELEASE AT TRUE CENTER', minRound: 6, timeLimit: 9, tuning: { tolerance: { easy: 18, medium: 12, hard: 8 } }, incompatibleRules: ['two-finger-third', 'alternate-sector', 'central-contact'], accessibility: 'Drag the sample and release it as close to the target center as possible.' }),
  interaction({ id: 'pressure-bar', name: 'Signal Load', kind: 'pressure-bar', category: 'TIMING', gesture: 'timing', instruction: 'LOCK THE SIGNAL LOAD', minRound: 5, timeLimit: 7, tuning: { targetValue: 0.72, tolerance: { easy: 0.14, medium: 0.1, hard: 0.07 } }, accessibility: 'Touch when the moving indicator overlaps the target load zone.' }),
  logic({ id: 'prime-tap', name: 'Prime Filter', kind: 'prime-tap', category: 'LOGIC', gesture: 'logic', instruction: 'SELECT ONLY PRIMES', minRound: 9, timeLimit: 11, accessibility: 'Select every prime number and no composite numbers, then confirm.' }),
  memory({ id: 'previous-shape', name: 'Previous Sample', kind: 'previous-shape', category: 'MEMORY', gesture: 'memory', instruction: 'SELECT THE PREVIOUS SHAPE', minRound: 10, timeLimit: 8, accessibility: 'Choose the geometric shape shown immediately before the current one.' }),
  memory({ id: 'disappearing-position', name: 'Spatial Recall', kind: 'disappearing-position', category: 'MEMORY', gesture: 'memory', instruction: 'RECALL THE COORDINATE', minRound: 8, timeLimit: 10, accessibility: 'Remember the marked grid coordinate and touch it after the marker disappears.' }),
  interaction({ id: 'screen-quadrant', name: 'Sector Response', kind: 'screen-quadrant', category: 'REACTION', gesture: 'tap', instruction: 'TOUCH LOWER LEFT', minRound: 4, timeLimit: 6, incompatibleRules: ['opposite-day', 'alternate-sector'], accessibility: 'Touch the requested lower-left sector of the response field.' }),
  interaction({ id: 'gesture-sequence', name: 'Motor Sequence', kind: 'gesture-sequence', category: 'COORDINATION', gesture: 'swipe', instruction: 'TAP / SWIPE / TAP', minRound: 12, timeLimit: 12, incompatibleRules: ['opposite-day', 'two-finger-third'], accessibility: 'Perform a tap, then a swipe, then another tap in the response field.' }),
  interaction({ id: 'alternating-taps', name: 'Lateral Alternation', kind: 'alternating-taps', category: 'COORDINATION', gesture: 'tap', instruction: 'LEFT / RIGHT / REPEAT', minRound: 8, timeLimit: 9, incompatibleRules: ['alternate-sector'], accessibility: 'Touch the left and right response pads in alternating order.' }),
  interaction({ id: 'dual-meters', name: 'Dual Calibration', kind: 'dual-meters', category: 'TIMING', gesture: 'timing', instruction: 'LOCK BOTH METERS', minRound: 14, timeLimit: 10, accessibility: 'Stop both independently moving meters inside their marked sectors.' }),
  logic({ id: 'size-order', name: 'Scale Ordering', kind: 'size-order', category: 'LOGIC', gesture: 'logic', instruction: 'SMALLEST TO LARGEST', minRound: 7, timeLimit: 9, accessibility: 'Touch the geometric samples from smallest to largest.' }),
  memory({ id: 'after-flashes', name: 'Counted Response', kind: 'after-flashes', category: 'TIMING', gesture: 'timing', instruction: 'TOUCH AFTER SIGNAL 04', minRound: 9, timeLimit: 10, accessibility: 'Count the flashes and touch immediately after the fourth signal.' }),
  logic({ id: 'system-check', name: 'Recovery Selection', kind: 'system-check', category: 'SPECIAL', gesture: 'logic', instruction: 'RESTORE THE SIGNAL', minRound: 15, timeLimit: 8, accessibility: 'Choose the correct recovery control on the simulated system interruption.' }),

  interaction({ id: 'bio-hold-1250', name: 'Motor Hold Short', kind: 'exact-hold', variant: 'SHORT WINDOW', category: 'TIMING', gesture: 'hold', instruction: 'HOLD FOR 1.250s', minRound: 6, timeLimit: 6, tuning: { targetMs: 1250, toleranceMs: { easy: 210, medium: 105, hard: 60 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Press and hold the sensor for exactly one point two five seconds.' }),
  interaction({ id: 'reactor-hold-2100', name: 'Heat Stabilization', kind: 'exact-hold', variant: 'LONG WINDOW', category: 'TIMING', gesture: 'hold', instruction: 'STABILIZE FOR 2.100s', minRound: 12, timeLimit: 7, tuning: { targetMs: 2100, toleranceMs: { easy: 260, medium: 130, hard: 75 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Hold the heat stabilization sensor for exactly two point one seconds.' }),
  interaction({ id: 'reverse-dial', name: 'Counter-Rotation Lock', kind: 'stop-needle', variant: 'COUNTER ROTATION', category: 'TIMING', gesture: 'timing', instruction: 'LOCK THE REVERSE NEEDLE', minRound: 9, timeLimit: 7, tuning: { targetAngleDeg: 232, tolerance: { easy: 30, medium: 19, hard: 12 } }, accessibility: 'Touch when the counter-rotating indicator enters the marked sector.' }),
  interaction({ id: 'bilateral-corners', name: 'Two-Hand Check', kind: 'simultaneous-tap', variant: 'WIDE SPAN', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'TOUCH OPPOSITE SENSORS', minRound: 11, timeLimit: 8, tuning: { requiredPointers: 2, toleranceMs: { easy: 170, medium: 105, hard: 65 } }, incompatibleRules: ['two-finger-third', 'single-contact', 'central-contact'], accessibility: 'Touch the lower-left and upper-right inset sensors with two distinct fingers at the same time.' }),
  interaction({ id: 'angle-swipe', name: 'Angular Vector', kind: 'angle-swipe', category: 'SWIPE', gesture: 'swipe', instruction: 'SWIPE AT 45 DEGREES', minRound: 8, timeLimit: 7, tuning: { targetAngleDeg: -45, tolerance: { easy: 24, medium: 15, hard: 9 } }, incompatibleRules: ['opposite-day'], accessibility: 'Swipe upward and right as close as possible to a forty-five degree angle.' }),
  interaction({ id: 'speed-swipe', name: 'Velocity Scan', kind: 'speed-swipe', category: 'SWIPE', gesture: 'swipe', instruction: 'SWIPE AT 900px/s', minRound: 10, timeLimit: 7, tuning: { targetVelocityPxPerSecond: 900, tolerance: { easy: 330, medium: 210, hard: 130 } }, incompatibleRules: ['opposite-day'], accessibility: 'Swipe across the field at approximately nine hundred pixels per second.' }),
  interaction({ id: 'clean-sensor', name: 'Sensor Cleaning', kind: 'scratch-scan', variant: 'INTERFERENCE', category: 'DRAG', gesture: 'drag', instruction: 'REMOVE THE INTERFERENCE', minRound: 6, timeLimit: 10, tuning: { revealThreshold: { easy: 58, medium: 68, hard: 76 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Continuously rub across the interference field until enough of the sensor is cleared.' }),
  interaction({ id: 'reveal-profile', name: 'Profile Reveal', kind: 'scratch-scan', variant: 'IDENTITY MASK', category: 'DRAG', gesture: 'drag', instruction: 'REVEAL THE HUMAN PROFILE', minRound: 13, timeLimit: 11, tuning: { revealThreshold: { easy: 62, medium: 72, hard: 80 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Rub across the identity mask until the hidden geometric human profile is revealed.' }),
  interaction({ id: 'draw-chevron', name: 'Chevron Trace', kind: 'draw-shape', variant: 'CHEVRON', category: 'PRECISION', gesture: 'drag', instruction: 'DRAW THE CHEVRON', minRound: 8, timeLimit: 9, tuning: { tolerance: { easy: 0.72, medium: 0.8, hard: 0.86 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Trace a single continuous chevron from the left marker through the center to the right marker.' }),
  interaction({ id: 'draw-ring', name: 'Ring Trace', kind: 'draw-shape', variant: 'CLOSED LOOP', category: 'PRECISION', gesture: 'drag', instruction: 'DRAW ONE CLOSED LOOP', minRound: 14, timeLimit: 10, tuning: { tolerance: { easy: 0.68, medium: 0.76, hard: 0.84 } }, incompatibleRules: ['two-finger-third'], accessibility: 'Draw one continuous closed loop around the calibration center.' }),
  interaction({ id: 'charge-level', name: 'Battery Calibration', kind: 'pressure-bar', variant: 'LOW TARGET', category: 'TIMING', gesture: 'timing', instruction: 'LOCK CHARGE AT 44%', minRound: 7, timeLimit: 7, tuning: { targetValue: 0.44, tolerance: { easy: 0.14, medium: 0.09, hard: 0.055 } }, accessibility: 'Touch when the moving charge indicator reaches forty-four percent.' }),
  interaction({ id: 'human-pulse', name: 'Human Pulse', kind: 'tap-on-beat', variant: 'RING INTERSECTION', category: 'TIMING', gesture: 'timing', instruction: 'TOUCH AT RING CONTACT', minRound: 9, timeLimit: 7, tuning: { toleranceMs: { easy: 145, medium: 92, hard: 58 } }, accessibility: 'Touch at the instant the expanding pulse ring meets the fixed ring.' }),
  interaction({ id: 'three-point-hold', name: 'Three-Point Stability', kind: 'multi-object-hold', variant: 'SIMULTANEOUS HOLD', category: 'MULTITOUCH', gesture: 'multi-touch', instruction: 'HOLD ALL THREE POINTS', minRound: 15, timeLimit: 10, pointerRequirement: { min: 3, max: 3 }, incompatibleRules: ['two-finger-third', 'single-contact'], accessibility: 'Place and maintain three different fingers on the three stability sensors.' }),
  logic({ id: 'visual-noise', name: 'Noise Anomaly Search', kind: 'odd-one-out', variant: 'INTERFERENCE', category: 'REACTION', gesture: 'logic', instruction: 'FIND PIX IN THE NOISE', minRound: 13, timeLimit: 9, accessibility: 'Find and touch the one PIX-shaped sample among the moving interference marks.' }),
]

export function getChallenge(id: string): ChallengeDefinition | undefined {
  return CHALLENGES.find(challenge => challenge.id === id)
}
